version: 2.1
orbs:
  saucelabs: saucelabs/connect@volatile
workflows:
  basic_workflow:
    jobs:
      - saucelabs/with_proxy:
          steps:
            - run: mvn clean verify allure:report -P grid -DsuiteXmlFile=smoke.suite.xml